(() => {
  console.log("JS is connected!")

  function logKeyCode(event){
    //debugger;
    // event is an object that is generated by any event
    // it contains all of the info about the event, what
    // element triggered it, where it occured on the page.
    //console.log(event.keyCode);

    let currentKey = document.querySelector(`div[data-key=
      "${event.keyCode}"]`);
    let currentAudioClip = document.querySelector(`audio[data-key=
      "${event.keyCode}"]`);

    if (!currentKey){return;}

    currentKey.classList.add("playing");
    currentAudioClip.currentTime = 0;
    currentAudioClip.play();
  }

  function removePlayingClass(event){
    // listen for the transition to end, then remoce playing class
    //debugger;
    if(event.propertyName !== "transform"){return;}

    event.target.classList.remove('playing');
  }

  const keys = Array.from(document.querySelectorAll('.key'));
  keys.forEach(key => key.addEventListener("transitionend", removePlayingClass));
  // try to get key pressed events
  window.addEventListener("keydown", logKeyCode);
})();
